# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

cirrus_cs40l2x-objs = cs40l2x.o cs40l2x-tables.o
obj-m += cirrus_cs40l2x.o
