# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/power/rt9426a_fg_mmi

rt9426a_fg_mmi-objs += rt9426a_battery.o
obj-m += rt9426a_fg_mmi.o
