# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include

EXTRA_CFLAGS += -DCONFIG_HW_RANDOM_IDQ250C2_TIMER
EXTRA_CFLAGS += -DCONFIG_HW_RANDOM_IDQ250C2_MISC_DEVICE

obj-m += qrng_hwrng.o
