# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include \
				-I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/input/misc/ets_bix_mmi

ifneq ($(filter m y,$(CONFIG_EGIS_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_EGIS_DRM_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif
#ifneq ($(filter m y,$(CONFIG_ET721_FOD)),)
#    EXTRA_CFLAGS += -DET721_FOD
#endif

ets_bix_mmi-y += etxxx_fp.o


obj-m += ets_bix_mmi.o

