# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

obj-m := leds_lm3697.o
leds_lm3697-objs += ti_lm3697.o
leds_lm3697-objs += ti_lm3697_backlight.o
leds_lm3697-objs += ti_lm3697_backlight_data.o
