ccflags-y += -Wall
ccflags-y += -I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/misc/moto_kern_prot
ccflags-y += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include
ccflags-y += -I$(ANDROID_BUILD_TOP)/kernel_platform/msm-kernel/include
ccflags-y += -I$(ANDROID_BUILD_TOP)/kernel_platform/msm-kernel/

moto_kern_prot-objs := moto_rkp_kickoff.o qcom_hvc.o

obj-m += moto_kern_prot.o
