# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

ifeq ($(filter m y, $(CONFIG_INPUT_DRV2624_HAPTICS)),)
obj-m += drv2624_mmi.o
endif
