# add -Wall to try to catch everything we can.
ifneq ($(filter m y,$(CONFIG_AF_NOISE_ELIMINATION)),)
	EXTRA_CFLAGS += -DCONFIG_AF_NOISE_ELIMINATION
endif

ifneq ($(filter y,$(CONFIG_AW8965_VIBRATOR_SHORT_WAV_ENABLE)),)
	EXTRA_CFLAGS += -DCONFIG_AW8965_VIBRATOR_SHORT_WAV_ENABLE
endif

EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include

obj-m += aw8695.o
