# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include \
		-I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/drivers/power/mmi_sc8549

obj-m += mmi_sc8549.o


