# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include \
		-I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/drivers/power/rt9467_chg_mmi

obj-m += rt9467_charger.o


