# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include \
		-I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/input/touchscreen/raydium_mmi

obj-m := raydium_mmi.o
raydium_mmi-objs += raydium_i2c_ts.o
