# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include \
		-I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/drivers/power/bq27426_fg_mmi

ifneq ($(filter m y,$(CONFIG_ATL_4000MAH_8A_BATTERY_PROFILE)),)
	EXTRA_CFLAGS += -DATL_4000MAH_8A_BATTERY_PROFILE
endif

ifneq ($(filter m y,$(CONFIG_SCUD_4000MAH_8A_BATTERY_PROFILE)),)
	EXTRA_CFLAGS += -DSCUD_4000MAH_8A_BATTERY_PROFILE
endif

ifneq ($(filter m y,$(CONFIG_ATL_LS40_1545MAH_BATTERY_PROFILE)),)
	EXTRA_CFLAGS += -DATL_LS40_1545MAH_BATTERY_PROFILE
endif

ifneq ($(filter m y,$(CONFIG_ATL_LS30_1255MAH_BATTERY_PROFILE)),)
	EXTRA_CFLAGS += -DATL_LS30_1255MAH_BATTERY_PROFILE
endif

ifneq ($(filter m y,$(CONFIG_ATL_NM40_712MAH_BATTERY_PROFILE)),)
	EXTRA_CFLAGS += -DATL_NM40_712MAH_BATTERY_PROFILE
endif

obj-m += bq27426_fg_mmi.o
