# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include \
				-I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/input/misc/rbs_fps_mmi

ifneq ($(filter m y,$(CONFIG_EGIS_PANEL_NOTIFICATIONS)),)
    EXTRA_CFLAGS += -DCONFIG_PANEL_NOTIFICATIONS
endif

ifneq ($(filter m y,$(CONFIG_ET721_FOD)),)
    EXTRA_CFLAGS += -DET721_FOD
endif

rbs_fps_mmi-y += etxxx_fp.o


obj-m += rbs_fps_mmi.o

