# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include

moto_f_usbnet-objs += f_usbnet.o
obj-m += moto_f_usbnet.o
