# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

ifneq ($(filter m y,$(CONFIG_USE_MMI_CHARGER)),)
	EXTRA_CFLAGS += -DUSE_MMI_CHARGER
	EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/power/mmi_charger
	KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../mmi_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
endif

ifneq ($(filter m y, $(ADAPTIVE_TOLERANCE_OPTIMIZATION)),)
	EXTRA_CFLAGS += -DADAPTIVE_TOLERANCE_OPTIMIZATION
endif

obj-m += qpnp_adaptive_charge.o
