# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/include
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/modules/drivers/power/qti_glink_charger

obj-m += smart_pen_charger.o

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../qti_glink_charger/$(GKI_OBJ_MODULE_DIR)/Module.symvers
