# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include

ifneq ($(filter m y,$(CONFIG_INPUT_AWINIC_HAPTIC)),)
	EXTRA_CFLAGS += -DCONFIG_INPUT_AWINIC_HAPTIC
endif

ifneq (,$(filter smith%,$(TARGET_PRODUCT)))
	EXTRA_CFLAGS += -DCONFIG_AW8697_BOOT_VIBRATION
endif

obj-m += aw8697.o
