# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(KERNEL_SRC)/../sm8475-modules/motorola/include \
		-I$(KERNEL_SRC)/../sm8475-modules/motorola/drivers/power/mmi_parallel_charger

obj-m += mmi_parallel_charger.o
mmi_parallel_charger-objs += mmi_charger_class.o
mmi_parallel_charger-objs += mmi_charger_core.o
mmi_parallel_charger-objs += mmi_charger_pump_policy.o
mmi_parallel_charger-objs += bq2597x_charger.o
mmi_parallel_charger-objs += qpnp_pmic_charger.o

#ifeq ($(CONFIG_MMI_PL_CP_POLICY), y)
#endif
